myblogz/blogg/urls.py
from django.urls import path
from . import views

urlpatterns = [path('', views.PostView.as_view()),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('review/<int:pk>/', views.AddComments.as_view(), name="add_comments"),
               path('<int:pk>/add_likes/', views.AddLike.as_view(), name="add_likes"),
               path('<int:pk>/del_likes/', views.DelLike.as_view(), name="del_likes")]

myblogz/myblogz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogg.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblogz/blogg/models.py
from django.db import models

#Posts
class Post(models.Model):
    # Information about the post
    title = models.CharField('Heading', max_length=100)
    textContent = models.TextField('Text')
    author = models.CharField('Author', max_length=100)
    date = models.DateField('Date of publication')
    image = models.ImageField('Images', upload_to='image/%Y')

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Record'
        verbose_name_plural = 'Records'

#Comments
class Comments(models.Model):
    email = models.EmailField()
    name = models.CharField('Name', max_length=50)
    text_comments = models.TextField('Comment Text', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Publication', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

#Likes
class Likes(models.Model):
    ip = models.CharField('IP-adress', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Publication', on_delete=models.CASCADE)

myblogz/blogg/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post, Likes
from .form import CommentsForm

#Class for output of posts
class PostView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/blog.html', {'post_list': posts})

#Class for separate post page
class PostDetail(View):
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post': post})

#class to add comments
class AddComments(View):
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

#Class to add likes
class AddLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')

#Class to delete like
class DelLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_client)
            lik.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

myblogz/templates/blog/blog.html
{% load static %}
<html>
<head>
	<title>MyBlogz</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Main</a></li>
			    <li><a href="/admin">Admin</a></li>
			    
			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">
				
				<div class="projects">
					<h3>Posts</h3>
					{% for post in post_list %}
					<div class="item">
						<p align="center">
							<img src="{{ post.image.url }}" width="400px" />
						<p>
						<div class="text left">
							<h4><a	href="{{ post.id }}">{{ post.title }}</a></h4>
							<p>{{ post.textContent }}</p>
							<p class="author">Author: {{ post.author }} </p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
					{% endfor %}
				</div>
			</div>

			<div class="cl_end">&nbsp;</div>
		</div>
		

	</div>
	
	<div id="footer">
		<p class="copy right">MyBlogz &copy;  2023 </p>
	</div>
</div>
</body>
</html>

myblogz/templates/blog/blog_detail.html
{% load static %}
<html>
<head>
	<title>MyBlogz</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Main</a></li>
			    <li><a href="/admin">Admin</a></li>

			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>{{ post.title }}</h3>
                  <p align="center">
                    <img src="{{ post.image.url }}" width="50%" />
                  </p>
					<div class="item">
						<div class="text center">
							<p class="text_content">{{ post.textContent }}</p>
							<p class="author">Author: {{ post.author }} </p>
						</div>
					</div>
				</div>
			</div>
			<div>
				<br>
				<p>Likes: {{ post.likes_set.all.count }}</p>
				<br>
				<a href="{% url 'add_likes' post.id %}" class="like">Like</a>
				<a href="{% url 'del_likes' post.id %}" class="dislike">Dislike</a>
			</div>
			<div class="form_comment">
				<h3>Leave comment</h3>
				<div>
					<form action="{% url 'add_comments' post.id %}" method="post">
						{% csrf_token %}
						<div>
							<label>Your comment</label>
							<textarea name="text_comments"></textarea>
						</div>
						<div>
							<input type="text" name="name">
							<label>Name *</label>
						</div>
						<div>
							<input type="email" name="email">
							<label>Email *</label>
						</div>
						<div>
							<input type="submit">
						</div>
					</form>
				</div>
				<div class="cl">&nbsp;</div>
			</div>

			<div>
				<p class="comments_p">COMMENTS</p>
				<div>
					{% for comment in post.comments_set.all %}
					<div class="view_comment">
						<h4>{{ comment.name }}</h4>
						<p>
							{{ comment.text_comments }}
						</p>
					</div>
					{% endfor %}
				</div>
			</div>

			<div class="cl">&nbsp;</div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">MyBlogz &copy;  2023 </p>
	</div>
</div>
</body>
</html>